# Generated by Django 4.1.5 on 2023-01-04 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_chat_id_alter_event_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chats',
            field=models.ManyToManyField(to='api.chat'),
        ),
    ]
