# Generated by Django 4.1.5 on 2023-01-04 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_profile_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='chats',
        ),
        migrations.RemoveField(
            model_name='school',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='team',
            name='chat',
        ),
        migrations.AddField(
            model_name='chat',
            name='event',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.event'),
        ),
        migrations.AddField(
            model_name='chat',
            name='members',
            field=models.ManyToManyField(to='api.profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='school',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.school'),
        ),
        migrations.AddField(
            model_name='chat',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.team'),
        ),
    ]
