# Generated by Django 4.1.5 on 2023-01-14 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_chat_members_alter_event_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='image',
            field=models.ImageField(default='default_school.png', upload_to='static/school_images'),
        ),
    ]
